# Generated by Django 4.2.30 on 2026-04-27 14:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_zone', models.CharField(blank=True, max_length=200, verbose_name='Zona')),
                ('notes', models.TextField(blank=True, verbose_name='Comentarios')),
                ('items', models.JSONField(default=list, verbose_name='Productos')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], db_index=True, default='nuevo', max_length=20, verbose_name='Estado')),
                ('seller_notes', models.TextField(blank=True, verbose_name='Notas del vendedor')),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('emoji', models.CharField(default='🥩', max_length=10, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price_label', models.CharField(default='Consultar', help_text='Ej: Consultar, $6.800, Precio mayorista', max_length=100, verbose_name='Precio')),
                ('unit', models.CharField(default='kg', help_text='Ej: kg, pieza, unidad', max_length=50, verbose_name='Unidad')),
                ('tag', models.CharField(blank=True, help_text='Ej: Al Vacío, Mayorista, Nuevo', max_length=50, verbose_name='Etiqueta')),
                ('active', models.BooleanField(default=True, verbose_name='Visible en catálogo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
