# Generated by Django 4.2.30 on 2026-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto del producto (jpg, png). Recomendado: 600x400px', null=True, upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='emoji',
            field=models.CharField(default='🥩', help_text='Se usa como fallback si no hay imagen', max_length=10, verbose_name='Emoji'),
        ),
    ]
