# Generated by Django 4.2.30 on 2026-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_product_image_alter_product_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la zona')),
                ('tipo', models.CharField(choices=[('verde', 'Envío estándar'), ('amarillo', 'Consultar costos'), ('rojo', 'Sin llegada')], default='verde', max_length=20, verbose_name='Tipo')),
                ('poligono_geojson', models.TextField(help_text='Datos geométricos en formato GeoJSON', verbose_name='GeoJSON')),
            ],
            options={
                'verbose_name': 'Zona de Entrega',
                'verbose_name_plural': 'Zonas de Entrega',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
